name: plerion

volumes:
  minio_data:
  postgres_data:
  cloudbeaver_data:
  uv_cache:

services:
  minio:
    image: docker.io/minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "${S3_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_KEY}"
      MINIO_BROWSER_REDIRECT_URL: "https://${DEVICE_NAME}-minioconsole.${DOMAIN}"
      MINIO_SERVER_URL: "https://${DEVICE_NAME}-minio.${DOMAIN}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 1s
      retries: 60

  minio-reverse-proxy:
    build: services/minio-reverse-proxy
    depends_on:
      - minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      DEVICE_NAME: "${DEVICE_NAME}"
      DOMAIN: "${DOMAIN}"

  initialize-minio:
    image: docker.io/minio/mc:latest
    restart: "no"
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY} && \
        mc mb --ignore-existing local/dev-captures
      "
    environment:
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"

  postgres:
    image: docker.io/library/postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q -h localhost -p 5432 -U $${POSTGRES_USER} -d postgres",
        ]
      interval: 1s
      timeout: 1s
      retries: 30

  initialize-cloudbeaver:
    build: tasks/initialize-cloudbeaver
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      CB_ADMIN_NAME: ${CLOUDBEAVER_ADMIN_USER}
      CB_ADMIN_PASSWORD: ${CLOUDBEAVER_ADMIN_PASSWORD}

  cloudbeaver:
    image: docker.io/dbeaver/cloudbeaver:latest
    depends_on:
      initialize-cloudbeaver:
        condition: service_completed_successfully
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway" # speeds up start up a little
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 1s
      timeout: 1s
      retries: 90

  create-database:
    build:
      dockerfile: services/database-manager/Dockerfile.compose
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
      cloudbeaver:
        condition: service_healthy
    volumes:
      - cloudbeaver_data:/mnt/efs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      BACKEND: docker
      CLOUDBEAVER_SERVICE_ID: plerion-cloudbeaver-1
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    entrypoint: >-
      uv run --no-sync python -m src.main
      --op create
      --name ${DATABASE_NAME}
      --owner-password ${DATABASE_OWNER_PASSWORD}
      --api-user-password ${DATABASE_API_USER_PASSWORD}
      --auth-user-password ${DATABASE_AUTH_USER_PASSWORD}
      --orchestration-user-password ${DATABASE_ORCHESTRATION_USER_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    environment:
      API_HOSTNAME: https://${DEVICE_NAME}-api.${DOMAIN}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: https://${DEVICE_NAME}-keycloak.${DOMAIN}
      KC_HOSTNAME_ADMIN: https://${DEVICE_NAME}-keycloak.${DOMAIN}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_DEBUG: true
    volumes:
      - ./services/keycloak/realm-export:/opt/keycloak/data/import:ro

  keycloak-reverse-proxy:
    build: services/keycloak-reverse-proxy
    depends_on:
      - keycloak
    ports:
      - "8080:8080"
    environment:
      DEVICE_NAME: ${DEVICE_NAME}
      DOMAIN: ${DOMAIN}

  visual-localization-system-api:
    build:
      dockerfile: services/visual-localization-system/api/Dockerfile
    depends_on:
      initialize-minio:
        condition: service_completed_successfully
      create-database:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
      - "5679:5678"
    volumes:
      - ./services/visual-localization-system/api:/app/services/visual-localization-system/api
      - ./services/visual-localization-system/models:/app/services/visual-localization-system/models
      - ./common:/app/common
      - uv_cache:/root/.cache/uv
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      BACKEND: docker
      KEYCLOAK_PUBLIC_HOST: https://${DEVICE_NAME}-keycloak.${DOMAIN}
      KEYCLOAK_INTERNAL_HOST: ${KEYCLOAK_INTERNAL_HOST}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_API_USER: ${DATABASE_NAME}_api_user
      DATABASE_AUTH_USER: ${DATABASE_NAME}_auth_user
      DATABASE_API_USER_PASSWORD: ${DATABASE_API_USER_PASSWORD}
      DATABASE_AUTH_USER_PASSWORD: ${DATABASE_AUTH_USER_PASSWORD}
      S3_ENDPOINT_URL: "https://${DEVICE_NAME}-minio.${DOMAIN}"
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      JOB_QUEUE_ARN: dummy
      RECONSTRUCTION_JOB_DEFINITION_ID: plerion-run-reconstruction
      FEATURES_JOB_DEFINITION_ID: plerion-extract-match-features
      RELOAD: true
      DEBUG: ${DEBUG_API}
      DEBUG_WAIT: ${DEBUG_WAIT_API}
      DEBUG_RECONSTRUCTION: ${DEBUG_RECONSTRUCTION}
      DEBUG_WAIT_RECONSTRUCTION: ${DEBUG_WAIT_RECONSTRUCTION}
      DEBUG_FEATURES: ${DEBUG_FEATURES}
      DEBUG_WAIT_FEATURES: ${DEBUG_WAIT_FEATURES}

  delete-database:
    profiles: ["tasks"]
    build:
      dockerfile: tasks/delete-database/Dockerfile

  run-reconstruction:
    profiles: ["tasks"]
    build:
      dockerfile: tasks/run-reconstruction/Dockerfile

  extract-match-features:
    profiles: ["tasks"]
    build:
      dockerfile: tasks/extract-match-features/Dockerfile
